// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEIa8wQtJnPrNwPLvbCxf_RusnNkHR-EY',
    appId: '1:762860467160:web:445e98ea43a17f3f10f8ad',
    messagingSenderId: '762860467160',
    projectId: 'involve-79dad',
    authDomain: 'involve-79dad.firebaseapp.com',
    storageBucket: 'involve-79dad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHlY9T9qSylIcNazGF80OVxUppefSmYiY',
    appId: '1:762860467160:android:bf721a9445640c5310f8ad',
    messagingSenderId: '762860467160',
    projectId: 'involve-79dad',
    storageBucket: 'involve-79dad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-JQSKp0vD4fEEKYKBPAdel29sna6CPfs',
    appId: '1:762860467160:ios:17dfa90919a6b5ee10f8ad',
    messagingSenderId: '762860467160',
    projectId: 'involve-79dad',
    storageBucket: 'involve-79dad.appspot.com',
    iosClientId: '762860467160-42q66t5akdpgnh47u9587gf1023f0lif.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackfest2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-JQSKp0vD4fEEKYKBPAdel29sna6CPfs',
    appId: '1:762860467160:ios:17dfa90919a6b5ee10f8ad',
    messagingSenderId: '762860467160',
    projectId: 'involve-79dad',
    storageBucket: 'involve-79dad.appspot.com',
    iosClientId: '762860467160-42q66t5akdpgnh47u9587gf1023f0lif.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackfest2023',
  );
}
